planner: AOgraph Class Reference
AOgraph Class Reference
class "AOgraph" for the AND-OR graph
#include <aograph.h>
Public Member Functions
AOgraph (string name)
constructor
string loadFromFile (string fileName)
load the graph description from a file
void printGraphInfo ()
display graph information
bool NodeFeasibiltyInfo (int)
bool NodeSolveInfo (int)
string NodeNameInfo (int)
string suggestNext (bool strategy)
suggest the node to solve
void solveByName (string nameNode)
solve a node, finding it by name
~AOgraph ()
destructor
Public Attributes
string gName
name of the graph
vector< AOnode > graph
set of nodes in the AND-OR graph
AOnode * head
pointer to the node = final assembly
vector< Path > paths
set of paths in the AND-OR graph
vector< int > pIndices
indices of the updated paths
vector< int > pUpdate
costs subtracted to the updated paths
Protected Member Functions
void addNode (string nameNode, int cost)
add a node in the graph
AOnode * findByName (string nameNode)
find a node by name
void updateNodeFeasibility ()
update the feasibility status of the nodes in the graph
int computeAddCost (AOnode &node, int hIndex)
compute the cost to add to a path
void generatePaths ()
generate all possible paths navigating the graph
string setupGraph ()
set up a graph
HyperArc * findHyperarc (AOnode &parent, AOnode &child)
find the hyperarc connecting a parent to a child node
int computeOverallUpdate (AOnode &node)
compute the overall update cost (intermediate step to update the path cost)
void updatePaths (AOnode &solved)
update all paths (update path costs when a node is solved)
int findOptimalPath ()
find the optimal path (long-sighted strategy)
Friends
class endorActionClass
Detailed Description
Definition at line 58 of file aograph.h.
Constructor & Destructor Documentation
AOgraph::AOgraph (string name)
constructor of class AOgraph
Parameters
[in] name name of the graph
Definition at line 515 of file aograph.cpp.
References gName, and head.
 {
     gName = name;
     head = NULL;
     //DEBUG:printGraphInfo();
 }
Member Function Documentation
void AOgraph::addNode (string nameNode, int cost) protected
add a node in the graph
Parameters
[in] nameNode name of the node
[in] cost generic node cost
Definition at line 117 of file aograph.cpp.
References graph.
 {
     // create the node
     AOnode toAdd(nameNode, cost);
     // add it to the set of nodes in the graph
     graph.push_back(toAdd);
 }
int AOgraph::computeAddCost (AOnode & node, int hIndex) protected
compute the cost to add to a path
Parameters
[in] node reference to the node to use for cost computation
[in] hIndex index of the node's hyperarc to use for cost computation
Returns
cost to add to a path
Definition at line 160 of file aograph.cpp.
References AOnode::arcs, and AOnode::nCost.
 {
     // 1. the cost is to be ADDED to the cost of the path
     // 2. cost = node.nCost + node.arcs[hIndex].hCost
     int cost = 0;
     // raise an error if the hyperarc index is out of bounds
     if (hIndex >= (int)node.arcs.size())
     {
         cout<<"[ERROR] The node has only " <<node.arcs.size() <<" hyperarcs."
             <<"Hyperarc index " <<hIndex <<" does not exist." <<endl;
         return -1;
     }
     // if hIndex == -1, the node is terminal
     if (hIndex == -1)
         cost = node.nCost;
     // otherwise, the cost to add is given by node.cost and hyperarc.cost
     else
         cost = node.nCost + node.arcs[hIndex].hCost;
     //DEBUG:cout<<"Node: " <<node.nName <<" - Cost: " <<cost <<endl;
     return cost;
 }
int AOgraph::computeOverallUpdate (AOnode & node) protected
compute the overall update cost (intermediate step to update the path cost)
Parameters
[in] node reference to the node to use for cost computation
Returns
overall update cost (to subtract from the path cost)
Definition at line 357 of file aograph.cpp.
References findHyperarc(), HyperArc::hCost, and AOnode::parents.
 {
     // 1. the cost is to be SUBTRACTED from the cost of the path
     // 2. the cost is computed as:
         // a. pathsCosts = set of the costs of the hyperarcs TO the current node
         // b. cost = max(pathsCosts)
     // N.B. the cost is to be subtracted from path[i] as:
     // 1. toSubtract = node.nCost + abs(pathsCosts[path_i] - cost);
     vector<int> pathsCosts;
     // for each parent node, find the cost of the hyperarc to the current node
     for (int i=0; i< (int)node.parents.size(); i++)
     {
         HyperArc* arc = findHyperarc(*node.parents[i], node);
         if (arc != NULL)
         {
             int arcCost = arc->hCost;
             pathsCosts.push_back(arcCost);
         }
     }
     /* DEBUG
     cout<<"maxUpdate is the max of: ";
     for (int i=0; i< (int)pathsCosts.size(); i++)
         cout<<pathsCosts[i] <<" ";
     cout<<endl;
     */
     // find the maximum in pathsCosts
     int cost = pathsCosts[0];
     for (int i=1; i< (int)pathsCosts.size(); i++)
         if (pathsCosts[i] > cost)
             cost = pathsCosts[i];
     //DEBUG:cout<<"maxUpdate = " <<cost <<endl;
     return cost;
 }
AOnode * AOgraph::findByName (string nameNode) protected
find a node by name
Parameters
[in] nameNode name of the node
Returns
pointer to the node with given name
Definition at line 129 of file aograph.cpp.
References graph.
 {
     AOnode* temp = NULL;
     for (int i=0; i< (int)graph.size(); i++)
     {
         if (graph[i].nName == nameNode)
         {
             temp = &graph[i];
             break;
         }
     }
     // issue a warning if the node has not been found
     if (temp == NULL)
         cout<<"[Warning] Name not found."
             <<"Did you really look for " <<nameNode <<"?" <<endl;
     return temp;
 }
HyperArc * AOgraph::findHyperarc (AOnode & parent, AOnode & child) protected
find the hyperarc connecting a parent to a child node
Parameters
[in] parent reference to the parent node
[in] child reference to the child node
Returns
index of the hyperarc connecting the parent to the child
Definition at line 327 of file aograph.cpp.
References AOnode::arcs, and AOnode::nName.
 {
     HyperArc* temp = NULL;
     for (int j=0; j< (int)parent.arcs.size(); j++)
     {
         for (int k=0; k< (int)parent.arcs[j].children.size(); k++)
         {
             if(parent.arcs[j].children[k]->nName == child.nName)
             {
                 temp = &parent.arcs[j];
                 //DEBUG:cout<<"Found index: " <<temp->hIndex <<endl;
                 break;
             }
         }
     }
     /* DEBUG
     // raise a warning if no hyperarc was found
     if (temp == NULL)
         cout<<"[WARNING] There is no hyperarc connecting " <<parent.nName
             <<" to " <<child.nName <<"." <<endl;
     */
     return temp;
 }
int AOgraph::findOptimalPath () protected
find the optimal path (long-sighted strategy)
Returns
index of the optimal path (minimum cost)
Definition at line 479 of file aograph.cpp.
References paths.
 {
     // raise an error if there are no paths
     if (paths.size() == 0)
     {
         cout<<"[ERROR] There are no paths navigating the graph. "
             <<"Did you run generatePaths()?" <<endl;
         return -1;
     }
     int index = 0;
     int cost = paths[0].pCost;
     for (int i=0; i< (int)paths.size(); i++)
     {
         // raise an error if there are not-complete paths
         if (paths[i].pComplete == false)
         {
             cout<<"[ERROR] The paths navigating the graph are not complete. "
                 <<"Did you run generatePaths()?" <<endl;
             return -1;
         }
         if (paths[i].pCost < cost)
         {
             cost = paths[i].pCost;
             index = i;
         }
     }
     cout<<"The optimal path is: " <<index <<endl;
     paths[index].printPathInfo();
     return index;
 }
string AOgraph::loadFromFile (string fileName)
load the graph description from a file
Parameters
[in] fileName name of the file with the graph description
Definition at line 525 of file aograph.cpp.
References AOnode::addArc(), addNode(), findByName(), gName, graph, head, and setupGraph().
 {
     // raise an error if the graph is not empty
     if (graph.size() != 0)
     {
         cout<<"[ERROR] The graph is not empty."
             <<"Do you really want to overwrite the current graph?" <<endl;
     }
     ifstream graphFile(fileName.c_str());
     cout <<"Loading graph description from file: " <<fileName <<endl;
     while (!graphFile.eof())
     {
         // the first line contains:
         // 1. the name of the graph
         // 2. the number N=numNodes of nodes
         // 3. the name of the head node (corresponding to the final assembly)
         string name;
         int numNodes;
         string headName;
         graphFile >>name >>numNodes >>headName;
 //  cout<<"info0: "<<graphFile<<endl;
         if (!graphFile)
             break;
         gName = name;
         // the next N lines contain the name and cost of all the nodes in the graph
         string nameNode;
         int cost;
         for (int i=0; i < numNodes; i++)
         {
             graphFile >>nameNode >> cost;
             if (!graphFile)
                 break;
             addNode(nameNode, cost);
         }
         // the next ?? lines contain the descriptions of the hyperarcs in the graph
         int hyperarcIndex = 0;
         while (!graphFile.eof())
         {
             AOnode* father;
             string nameFather;
             int numChildren;
             int hyperarcCost;
             vector<AOnode*> childNodes;
             graphFile >>numChildren >>nameFather >>hyperarcCost;
             if (!graphFile)
                 break;
             father = findByName(nameFather);
             //DEBUG:cout<<"nameFather = " <<nameFather <<endl;
             // the next numChildren lines contain the names of the child nodes
             for (int i=0; i < numChildren; i++)
             {
                 AOnode* temp;
                 string nameChild;
                 graphFile >>nameChild;
                 if (!graphFile)
                     break;
                 temp = findByName(nameChild);
                 childNodes.push_back(temp);
             }
             father->addArc(hyperarcIndex, childNodes, hyperarcCost);
             hyperarcIndex = hyperarcIndex+1;
         }
         // identify the head node in the graph
         head = findByName(headName);
     }
     graphFile.close();
     // set up the graph (nodes feasibility, paths costs)
     string intit_suggestion;
     intit_suggestion=setupGraph();
     cout<<"****************"<<endl;
     return intit_suggestion;
 }
string AOgraph::setupGraph () protected
printGraphInfo();
Definition at line 299 of file aograph.cpp.
References generatePaths(), paths, suggestNext(), and updateNodeFeasibility().
 {
     // update the feasibility status of the nodes in the graph
     updateNodeFeasibility();
     // generate all paths navigating the graph
     generatePaths();
     // set the "checked" property of the nodes in the paths to false
     // NOTE: during execution, "checked" is used to mark the solved nodes
     for (int i=0; i < (int)paths.size(); i++)
         for (int j=0; j < (int)paths[i].checkedNodes.size(); j++)
             paths[i].checkedNodes[j] = false;
     for (int i=0; i < (int)paths.size(); i++)
         paths[i].printPathInfo();
     // identify the first suggestion to make (long-sighted strategy chosen BY DEFAULT)
     string init_suggestion;
     init_suggestion=suggestNext(true);
     return init_suggestion;
 }
void AOgraph::solveByName (string nameNode)
solve a node, finding it by name
Parameters
[in] nameNode name of the node
printGraphInfo();
cout<<endl <<"Updated paths: " <<endl; for(int i=0; i< (int)pUpdate.size(); i++) cout<<"Path index: " <<pIndices[i] <<" - Benefit: " <<pUpdate[i] <<endl;
Definition at line 672 of file aograph.cpp.
References findByName(), head, AOnode::nSolved, AOnode::setSolved(), updateNodeFeasibility(), and updatePaths().
 {
     AOnode* solved = findByName(nameNode);
     bool result = solved->setSolved();
     updateNodeFeasibility();
     // report that the graph has been solved if the solved node is the head node
     if (head->nSolved == true)
     {
         cout<<"[REPORT] The graph is solved (head node solved)." <<endl;
         return;
     }
     // update the path information (cost) of all paths
     if (result == true)
         updatePaths(*solved);
 }
string AOgraph::suggestNext (bool strategy)
suggest the node to solve
Parameters
[in] strategy "0" = short-sighted, "1" = long-sighted
Returns
name of the suggested node
Definition at line 637 of file aograph.cpp.
References findOptimalPath(), head, AOnode::nName, AOnode::nSolved, paths, pIndices, and pUpdate.
 {
     // issue a warning if the graph has been solved already
     if (head->nSolved == true)
     {
         cout<<"[WARNING] The graph is solved. No suggestion possible." <<endl;
         return "end";
     }
     int optimalPathIndex = 0;
     // short-sighted strategy:
     // pick the path which received the highest benefit from the last action
     if (strategy == false)
     {
         // find the path with highest benefit from last action
         for (int i=1; i< (int)pUpdate.size(); i++)
             if (pUpdate[i] > pUpdate[optimalPathIndex])
                 optimalPathIndex = pIndices[i];
     }
     // long-sighted strategy:
     // pick the path which minimizes the cost to completion
     if (strategy == true)
         optimalPathIndex = findOptimalPath();
     AOnode* suggestion = paths[optimalPathIndex].suggestNode();
     cout<<"ENDOR suggestion: " <<endl
         <<"Suggested path = " <<optimalPathIndex <<endl
         <<"Suggested node = " <<suggestion->nName <<endl;
     return suggestion->nName;
 }
void AOgraph::updatePaths (AOnode & solved) protected
update all paths (update path costs when a node is solved)
Parameters
[in] solved reference to the solved node (to use for paths costs update)
Definition at line 398 of file aograph.cpp.
References computeOverallUpdate(), findHyperarc(), HyperArc::hCost, HyperArc::hIndex, AOnode::nCost, AOnode::nName, AOnode::parents, paths, pIndices, and pUpdate.
 {
     // update the path information (cost) of EACH path as:
     // toSubtract = solved.nCost + overall_update - path_i_update;
     // path[i].cost = path[i].cost - toSubtract;
     pIndices.clear();
     pUpdate.clear();
     int toSubtract = solved.nCost + computeOverallUpdate(solved);
     //DEBUG:cout<<"solved.nCost = " <<solved.nCost <<endl;
     //DEBUG:cout<<"maxUpdate = " <<computeOverallUpdate(solved) <<endl;
     // find all paths which include the solved node
     vector<int> withChild;
     for (int i=0; i < (int)paths.size(); i++)
         for (int j=0; j< (int)paths[i].pathNodes.size(); j++)
             if(paths[i].pathNodes[j]->nName == solved.nName)
                 withChild.push_back(i);
     /* DEBUG
     cout<<"Paths with solved node: ";
     for (int i=0; i < (int)withChild.size(); i++)
         cout<<"Path index: " <<withChild[i] <<" ";
     cout<<endl;
     */
     // find the paths including the solved node AND any of its parents
     vector<int> withBoth;
     int toAdd;
     for (int i=0; i < (int)withChild.size(); i++)
     {
         for (int j=0; j < (int)solved.parents.size(); j++)
             for (int k=0; k < (int)paths[withChild[i]].pathNodes.size(); k++)
                 if(paths[withChild[i]].pathNodes[k]->nName == solved.parents[j]->nName)
                     toAdd = withChild[i];
         // make sure that paths are added only ONCE
         if ( std::find(withBoth.begin(), withBoth.end(), toAdd) == withBoth.end() )
             withBoth.push_back(toAdd);
     }
     /* DEBUG
     cout<<"Paths with solved node & any parent: ";
     for (int i=0; i < (int)withBoth.size(); i++)
         cout<<"Path index: " <<withBoth[i] <<" ";
     cout<<endl;
     */
     // find the paths containing a DIRECT LINK between the solved node and a parent
     for (int i=0; i < (int)withBoth.size(); i++)
     {
         for (int j=0; j < (int)paths[withBoth[i]].pathNodes.size(); j++)
         {
             HyperArc* arc = findHyperarc(*paths[withBoth[i]].pathNodes[j], solved);
             // update the path cost (if there is a direct link in THIS path)
             if (arc != NULL)
             {
                 for (int k=0; k < (int)paths[withBoth[i]].pathArcs.size(); k++)
                 {
                     if (paths[withBoth[i]].pathArcs[k] == arc->hIndex)
                     {
                         // compute "path_i_update"
                         int pathUpdate = arc->hCost;
                         //DEBUG:cout<<"pathUpdate = " <<pathUpdate <<endl;
                         int thisSubtract = toSubtract - pathUpdate;
                         // update the cost of the path
                         paths[withBoth[i]].updatePath(solved.nName, thisSubtract);
                         // save the index & subtracted cost of the updated path
                         pIndices.push_back(withBoth[i]);
                         pUpdate.push_back(pathUpdate);
                         break;
                     }
                 }
             }
         }
     }
 }
The documentation for this class was generated from the following files:
include/aograph.h
include/aograph.cpp